theme: jekyll-theme-slate
title: All-Inside
description: <font size="5"> Detection and Estimation of Any Type of Break/Change-Point in One Code</font> 
baseURL: "https://Change-Point_All-Inside.github.io"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
